server:
  port: 8888

logging:
  path: logs
  file: Desktop/userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: tqx123456

mybatis:
  type-aliases-package: com.course.domain
  mapper-locations:
    - mapper/*